spring:
  application:
    name: es.indra.quartz
    port: 28080
---
es:
  indra:
    quartz:
      enabled: true
      cronExpression: 0 0/5 * * * ?
---
org:
  quartz:
    scheduler:
      instanceName: es.indra.quartz.cimacg
      instanceId: AUTO
      instanceIdGenerator: org.quartz.simpl.SimpleInstanceIdGenerator
    threadPool:
      threadCount: 10
      threadPriority: 5
      class: org.quartz.simpl.SimpleThreadPool
    jobStore:
      misfireThreshold: 60000
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      useProperties: false
      dataSource: quartzds
      tablePrefix: QRTZ_
      isClustered: true
      clusterCheckinInterval: 20000
      driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
    dataSource:
      quartzds:
        user: ${QRTZ_SPRING_DATASOURCE_USERNAME:QUARTZ}
        password: ${QRTZ_SPRING_DATASOURCE_PASSWORD:QUARTZ}
        URL: ${QRTZ_SPRING_DATASOURCE_URL:jdbc:oracle:thin:@192.168.56.1:11521/ORCL}
        driver: ${QRTZ_SPRING_DATASOURCE_DRIVER:oracle.jdbc.OracleDriver}
        provider: OracleODP
